# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('optout', models.BooleanField()),
            ],
        ),
    ]
