# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='seller',
            field=models.CharField(default='admin', max_length=40),
            preserve_default=False,
        ),
    ]
