# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspic',
            name='uploader_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
