# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0002_cuspic_uploader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='uploader_id',
            field=models.CharField(max_length=8),
        ),
    ]
