# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0003_auto_20190704_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
