# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0004_auto_20190722_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspic',
            name='username',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
