# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0005_cuspic_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='uploader_id',
            field=models.IntegerField(max_length=8),
        ),
    ]
