# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0006_auto_20190801_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='uploader_id',
            field=models.IntegerField(),
        ),
    ]
