# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0007_auto_20190801_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='uploader_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
