# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0008_auto_20190813_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuspic',
            old_name='uploader_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cuspic',
            name='username',
        ),
    ]
