# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0009_auto_20190813_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuspic',
            name='wm_image',
            field=models.ImageField(blank=True, upload_to='watermarks'),
        ),
    ]
