# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0010_cuspic_wm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='wm_image',
            field=models.ImageField(blank=True, upload_to='media/images/watermarks'),
        ),
    ]
