# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 22:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuspic', '0015_auto_20190906_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuspic',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Must be > 0.35', max_digits=6, validators=[django.core.validators.MinValueValidator(0.35)]),
        ),
    ]
